# Training config for compound vowel split model
#
# This configuration is used to train a split model that can identify
# split points within compound vowels.
#
# Usage:
# 1. First binarize your data with split_binarize_config.yaml
# 2. Run: python train.py -c configs/split_train_config.yaml -p pretrained_model.ckpt
#
# The resulting model can be used with split_infer.py to split compound vowels

model_name: split_model

# settings
float32_matmul_precision: high
random_seed: 114514

# dataloader
dataloader_workers: 0
dataloader_prefetch_factor: 2
oversampling_weights: [ 1, 1, 1 ] # full_label, weak_label, no_label
batch_max_length: 100 # unit: seconds
binning_length: 1000 # unit: seconds
drop_last: False

# model
model:
  hidden_dims: 128
  down_sampling_factor: 3
  down_sampling_times: 7
  channels_scaleup_factor: 1.5

optimizer_config:
  total_steps: 100000
  weight_decay: 0.1
  lr:
    backbone: 0.0005
    head: 0.0005
  freeze:
    backbone: False
    head: False

loss_config:
  losses:
    weights: [10.0, 0.1, 0.01, 0.1, 1.0, 1.0, 5.0]
    enable_RampUpScheduler: [False,False,False,True,True,True,True]
  function:
    num_bins: 10
    alpha: 0.999
    label_smoothing: 0.08
    pseudo_label_ratio: 0.3

# trainer
accelerator: auto
devices: auto
precision: bf16-mixed
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
val_check_interval: 500
